name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [21.x]
        module: [core-control, gate, timetable]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./${{ matrix.module }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          working-directory: ./${{ matrix.module }}
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          pwd
          npm ci
      - run: npm run build --if-present
      - run: npm run build:dll --if-present
      - run: npm test
